### ISSUE TITLE
Tracking Issue for DocEditor

### ISSUE THREAD

**Issue by zuobaoquan** [devjetsoftware/public#10]
These issues for IE-based doc editor.

- [ ] Filter not persistent (Show Protected/Inherited)
- [ ] Expand/Collapse icon not toggled
- [ ] Syntax highlight not work
- [ ] No Spelling check
- [ ] Triple-clicking not work
- [ ] Select all and delete makes editor broken
- [ ] Open file links with the default shell command (enhancement)
